#TODO: set actual initial positions

initial_positions:
  fr_theta1: 0.5
  fr_theta2: 0.5
  fr_theta3: 0.5
  fl_theta1: 0.5
  fl_theta2: 0.5
  fl_theta3: 0.5
  rr_theta1: 0.5
  rr_theta2: 0.5
  rr_theta3: 0.5
  rl_theta1: 0.5
  rl_theta2: 0.5
  rl_theta3: 0.5